### ISSUE TITLE
版本疑问

### ISSUE THREAD

**Issue by nckf** [demoshang/autojs-replace-inrt#2]
作者你好，首先感谢你的付出～
是这样的我正想做个 PC 端打包工具，包括 4.x 7.x 8.x，
因为打包要传到模拟器上很麻烦，咱不考虑离线加密功能。
因而找到了本项目，想问下这个项目最高支持到 `Auto.js` 版本是多大？
如果我像实现全版本打包到话有什么思路呢～ 感谢

**Comment by demoshang** [comment]
这个项目原理是通过 `Auto.js` 源码替换实现的打包, 也就是通过 `git clone https://github.com/hyb1996/Auto.js.git` 然后去找到 `inrt` 目录替换代码, 最后 `./gradlew :inrt:assembleDebug` 构建APP的, 具体可以看 [build.yml](https://github.com/demoshang/autojs-scripts/blob/master/.github/workflows/build.yml#L29-L55)

> 最高支持到 Auto.js 版本是多大
无关版本, 只关心源码结构是否更新

> 全版本打包
不好意思, 没有思路,  对 `Android` 不熟, 半路研究的这个替换方法....
